stackoverflow/forum/urls.py
from django.urls import path
from forum.views import HomeView, QuestionDetailView, QuestionCreateView, CreateUpdateView, CreateDeleteView

app_name = 'forum'

urlpatterns = [
    path('', HomeView.as_view(), name ='home'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('ask/', QuestionCreateView.as_view(), name='question-add'),
    path('question/<int:pk>/edit/', CreateUpdateView.as_view(), name = 'question-edit' ),
    path('question/<int:pk>/delete/', CreateDeleteView.as_view(), name = 'question-delete' ),
]

stackoverflow/stackoverflow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls'))
]

stackoverflow/forum/models.py
from django.db import models
from django.urls import reverse
from users.models import User
# Create your models here.

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=120)
    text = models.TextField()
    views = models.PositiveBigIntegerField(default=0, blank=True)

    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('forum:question-detail', kwargs={'pk': self.pk})

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=120)
    question = models.ManyToManyField(Question, blank=True)

stackoverflow/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

stackoverflow/forum/forms.py
from django import forms
from forum.models import Question, Answer

class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'title',
            'text',
            'user',
        ]

stackoverflow/forum/views.py
from django.shortcuts import render, redirect 
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView
from forum.models import Question
from forum.forms import QuestionCreateForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class HomeView(ListView):
    model = Question
    template_name = 'forum/question_list.html'

class QuestionDetailView(DetailView):
    model = Question
    template_name = 'forum/question_detail.html'


# def create_question_views(request):
#     if request.method == 'GET':
#         return render (
#                 request, 
#                 'forum/question_add.html',
#             {
#                 'form' : QuestionCreateForm(),
#             })
#     else:
#         form = QuestionCreateForm(request.POST)

#         if form.is_valid:
#             form.save()
#             return redirect('forum:home')

#         return render (
#                 request, 
#                 'forum/question_add.html',
#             {
#                 'form' : form,
#             })
 
class QuestionCreateView(LoginRequiredMixin,CreateView):
    model = Question
    fields = [
        'title', 'text'
    ]
    success_url = reverse_lazy('forum:home')
    template_name = 'forum/question_add.html'

    def form_valid(self, form):
        self.object: Question = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class CreateUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = 'forum/question_edit.html'
    fields = [
        'title', 'text'
    ]

    def get_queryset(self):
        if self.request.user.is_staff: 
            return Question.objects.all()
        return Question.objects.filter(user = self.request.user)


class CreateDeleteView(LoginRequiredMixin, DeleteView):
    model = Question
    fields = [
        'title', 'text'
    ]
    success_url = reverse_lazy('forum:home')
    def get_queryset(self):
        if self.request.user.is_staff: 
            return Question.objects.all()
        return Question.objects.filter(user = self.request.user)

stackoverflow/users/views.py
from django.shortcuts import render

# Create your views here.

stackoverflow/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <div>
        <form class="d-flex" role="search">
            <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search"
            <button class="btn btn-outline-success" type="submit">Search</button>
    </div>

    <main>
        {% block content %}
            
        {% endblock %}
    </main>
</body>
</html>

stackoverflow/templates/forum/question_add.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form method ="POST">
        <h4>{{ request.user }}</h4>
        {% csrf_token %}
        {{form.as_p}}

        <div><button type ='submit'>Ask</button></div>
        
    </form>
</div>

{% endblock content %}

stackoverflow/templates/forum/question_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form method ="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{object}}"?</p>
        {{form}}
        <a href ="{{object.get_absolute_url}}" class="btn btn-success" type ="submit">Go back</a>
        <button class ="btn btn-danger"type = "submit">Delete</button>

        
    </form>
</div>

{% endblock content %}

stackoverflow/templates/forum/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div class ='container-fluid w-75'>
        <div class = "d-flex justify-content-between">
            <h2>{{question.title}}</h2>
            {% if question.user == request.user %} 
                <a href={% url 'forum:question-edit' question.pk %} class="btn btn-primary">Edit</a>
                <a href={% url 'forum:question-delete' question.pk %} class="btn btn-primary">Delete</a>
             {% endif %} 
        </div


        <small>{{question.user}} &mdash; {{question.create_time}}</small
            <p>
         {{question.text}}</p>
         <small>{{question.views}} Views</small>
    </div
</div>
{% endblock content %}

stackoverflow/templates/forum/question_edit.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form method ="POST">
        {% csrf_token %}
        {{form.as_p}}
        
    </form>
</div>

{% endblock content %}

stackoverflow/templates/forum/question_list.html
{% extends 'base.html' %}

{% block content %}
<div>
    <a href ='/ask/'>Add Question</a>
<div>

    {% for question in question_list %}
        <h2>{{question.title}}</h2>
        <small>{{question.user}} &mdash; {{question.create_time}}</small
            <p>
         {{question.text |slice:100}} ...</p>
         <a href ='/question/{{ question.pk }}'>Read More</a>
         <div>
            {% for tag in question.tag_set.all %}
                <span class="badge bg-primary">{{ tag.name }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    
</div>

{% endblock content %}